# Generated by Django 4.0.4 on 2022-07-21 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JOB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('short_description', models.TextField()),
                ('employees_range', models.IntegerField()),
                ('job_title', models.TextField()),
                ('job_posted_timestamp', models.DateTimeField()),
                ('address', models.TextField()),
                ('job_type', models.TextField()),
                ('job_source_url', models.TextField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
