# Generated by Django 4.0.4 on 2022-07-21 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startupjobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='company_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='job',
            name='employees_range',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='short_description',
            field=models.TextField(default='', null=True),
        ),
    ]
