# Generated by Django 4.0.4 on 2022-07-21 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startupjobs', '0002_alter_job_company_name_alter_job_employees_range_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_posted_timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
